name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "<NOTES_KV_BINDING_ID>" },
  { binding = "SHARE", id = "<SHARE_KV_BINDING_ID>" }
]